version: 0.2

env:
  parameter-store:
    AWS_REGION: "/lab/AWS_REGION"
    ECR_REGISTRY: "/lab/ECR_REGISTRY"
    ECR_REPOSITORY: "/lab/ECR_REPOSITORY"

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY  
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t lab/front  . 
      - docker tag $ECR_REPOSITORY:latest $ECR_REGISTRY/$ECR_REPOSITORY:latest 
  post_build:
    commands:
      - echo Pushing image to ECR...
      - docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
      - echo Writing image definitions file...
      - printf '[{"name":"frontend","imageUri":"%s"}]' $ECR_REGISTRY/$ECR_REPOSITORY:latest > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
